blog/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:idBlog>', views.detail_blog, name='detailBlog'),
    path('login', views.auth, name='login'),
    path('register', views.register, name='register'),
    path('create_blog', views.create_blog, name='createBlog'),
    path('update_blog/<int:idBlog>', views.update_blog, name='updateBlog'),
    path('about', views.profile, name='profile')
]

blog_app_fe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

blog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'blog/main.html')

def detail_blog(request,idBlog):
    return render(request,'blog/detail_blog.html')

def auth(request):
    return render(request, 'blog/login.html')

def register(request):
    return render(request, 'blog/register.html')

def create_blog(request):
    return render(request, 'blog/create_blog.html')

def update_blog(request, idBlog):
    return render(request, 'blog/update_blog.html')

def profile(request):
    return render(request, 'blog/profile.html')

blog/templates/blog/create_blog.html
{% extends 'base.html' %} {% load static %} 

{% block title %}
Create Blog
{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'blog/css/style.css' %}" />
{% endblock head %}


{% block content %}
<section>
  <div class="container-fluid">
      <div class="container-sm">
          <div id="title">
              <h1>Create Your Blog 💛</h1>
              <hr>
          </div>
 
            <div class="mb-3">
              <label class="form-label">Blog Title</label>
              <input id="blog-title" class="form-control" placeholder="Judul Blog" required>
            </div>
            <div class="mb-3">
              <label class="form-label">Content</label>
              <textarea id="blog-content" rows="4" class="form-control" placeholder="Tulis komentar..." required></textarea>
            </div>
            <button id="create-button" type="submit" class="btn btn-primary">Create</button>

      </div>
  </div>
</section>

{% endblock content %}

{% block script %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'blog/js/create_blog.js'%}"></script>
{% endblock script %}

blog/templates/blog/detail_blog.html
{% extends 'base.html' %} {% load static %} 

{% block title %}
Blog Detail
{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'blog/css/style.css' %}" />
{% endblock head %}


{% block content %}
<section>
  <div class="container-fluid">
      <div class="row">
          <div class="col-lg-8">
            <section class="blog-data">

            </section>
          </div>
          <div class="col-lg-4">
              <section>
                  <div id="title">
                        <h1>Komentar</h1>
                        <hr>
                  </div>
                  <div class="card">
                      <div class="card-body">
                        <textarea id="komentar-area" rows="4" name="comment" form="usrform" placeholder="Tulis komentar..."></textarea>
                        <button id="komentar-content" type="button" class="btn btn-primary">Post Komentar</button>
                        <section class="list-komentar">
  
                        </section>
                      </div>
                  </div>
              </section>
          </div>
      </div>
  </div>
</section>

{% endblock content %}

{% block script %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'blog/js/detail_blog.js'%}"></script>
{% endblock script %}

blog/templates/blog/login.html
{% extends 'base.html' %} {% load static %} 

{% block title %}
Login
{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'blog/css/auth.css' %}" />
{% endblock head %}


{% block content %}
<section>
  <div class="container-fluid">
      <div class="container-sm">
          <div id="title">
              <h1>Login</h1>
              <hr>
          </div>
          <div class="mb-3">
            <label class="form-label">username</label>
            <input id="username" type="email" class="form-control" id="exampleInputEmail1" placeholder="ex : eren.yeager">
          </div>
          <div class="mb-3">
            <label class="form-label">Password</label>
            <input id="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="your password">
          </div>
          <button id="login-button" type="button" class="btn btn-primary">Login</button>
          <p id="register">Don't have account yet? <a href="{% url 'blog:register' %}" class="register">Register</a>!</p>
      </div>
  </div>
</section>

{% endblock content %}

{% block script %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'blog/js/login.js'%}"></script>
{% endblock script %}

blog/templates/blog/main.html
{% extends 'base.html' %} {% load static %}
{% block title %} 
Main 
{% endblock title %} 

{% block head %}
<link rel="stylesheet" href="{% static 'blog/css/style.css' %}" />
{% endblock head %} 

{% block content %}
<section>
  <div class="container-fluid">
    <div id="title">
      <h1>List of Blogs</h1>
      <hr />
    </div>
    <section class="penulis-related-createblog">
      <!-- FOR PENULIS ONLY -->
    </section>
    <section class="list-blog">

    </section>
  </div>
</section>

{% endblock content %} 

{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'blog/js/main.js'%}"></script>
{% endblock script %}

blog/templates/blog/profile.html
{% extends 'base.html' %} {% load static %} 

{% block title %}
Arya Profile
{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'blog/css/style.css' %}" />
{% endblock head %}


{% block content %}
<section>
  <div class="container-fluid">
      <div class="container-sm">
          <div id="title">
              <p class="h1">Writer's Profile</p>
              <hr>
          </div>
          <img id="my_photo" src="{% static 'mine.png' %}" alt="">
          <div class="data">
            <h3>Aryaputra Athallah</h3>
            <strong>TTL :</strong> Jakarta, 21 Desember 2000 <br>
            <strong>Age : </strong> 21<br>
            <strong>Location : </strong> Bogor<br>
          </div>
          <div class="about-me">
            <h3>About Me</h3>
            <p>My name is Arya, I am a student of Fasilkom UI. I am interested in several fields such as photography, videography, design, video editing and web development. I'm still learning to master all these fields</p>
          </div>
          <div class="experience">
            <h3>Experiences</h3>
            <strong>Campaign.id : </strong> Backend Developer Intern (2021 - now) <br>
            <strong>Compfest : </strong> Volunteer Lead of Startup Academy (2021) <br>
            <strong>Educare 2021 :</strong> VPIC of Workshop Division (2020 - 2021) <br>
            <strong>Pengenalan Mahasiswa Baru (PMB) Fasilkom : </strong> VPIC of Documentation Division 
          </div>
      </div>
  </div>
</section>

{% endblock content %}

{% block script %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock script %}

blog/templates/blog/register.html
{% extends 'base.html' %} {% load static %} 

{% block title %}
Register
{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'blog/css/auth.css' %}" />
{% endblock head %}


{% block content %}
<section>
  <div class="container-fluid">
      <div class="container-sm">
          <div id="title">
              <h1>Register</h1>
              <hr>
          </div>
          <div class="mb-3">
            <label class="form-label">Nama Lengkap</label>
            <input id="namaLengkap" class="form-control"  placeholder="ex : Eren Yeager">
          </div>
          <div class="mb-3">
            <label class="form-label">username</label>
            <input id="username" class="form-control" placeholder="ex : eren.yeager">
          </div>
          <div class="mb-3">
            <label class="form-label">Password</label>
            <input id="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="your password">
          </div>
          <button id="register-button" type="button" class="btn btn-primary">Register</button>
          <p id="register">Have account already? <a href="{% url 'blog:login' %}" class="login-nav-button">Login</a>!</p>
      </div>
  </div>
</section>

{% endblock content %}

{% block script %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'blog/js/register.js'%}"></script>
{% endblock script %}

blog/templates/blog/update_blog.html
{% extends 'base.html' %} {% load static %} 

{% block title %}
Update Blog
{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'blog/css/style.css' %}" />
{% endblock head %}


{% block content %}
<section>
  <div class="container-fluid">
      <div class="container-sm">
          <div id="title">
              <h1>Update Your Blog 💛</h1>
              <hr>
          </div>
            <div class="mb-3">
              <label class="form-label">Blog Title</label>
              <input id="blog-title" class="form-control" placeholder="Judul Blog" required>
            </div>
            <div class="mb-3">
              <label class="form-label">Content</label>
              <textarea id="blog-content" rows="4" class="form-control" placeholder="Tulis komentar..." required></textarea>
            </div>
            <button id="update-button" type="submit" class="btn btn-primary">Update</button>
      </div>
  </div>
</section>

{% endblock content %}

{% block script %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'blog/js/update_blog.js'%}"></script>
{% endblock script %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- font awesome -->
  <script src="https://kit.fontawesome.com/fb1ce7db1a.js" crossorigin="anonymous"></script>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous" />

  <!-- font  -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">

  <!-- Our CSS -->
  <link rel="stylesheet" href="{% static 'navbar.css' %}" />

  <!-- JQUERY -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>

  <title>{% block title %}{% endblock %} | BlogRistekAR</title>

  {% block head %} {% endblock %}
</head>

<body>
  {% include 'navbar.html' %} {% block content %} {% endblock %}
</body>
<script type="text/javascript" src="{% static 'navbar.js'%}"></script>
{% block script %} {% endblock %}

</html>

templates/navbar.html
{% load static %}

<section id="title2">
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-dark">
      <a class="navbar-brand" href="{% url 'blog:index' %}">Arya Blogger</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="{% url 'blog:profile' %}" class="nav-link">About Arya</a>
          </li> 
          <div class="drop-profile">
          </div>
          <li class="nav-item auth">
            <a href="{% url 'blog:login' %}" class="btn download-button auth-stuff">Login</a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</section>

<script
  src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
  integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
  crossorigin="anonymous"
></script>
<script
  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
  crossorigin="anonymous"
></script>
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
  integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
  crossorigin="anonymous"
></script>